// India tier 1 / 2 / 3 cities for programmatic SEO pages.
export type City = { slug: string; name: string; state: string; tier: 1 | 2 | 3 };

export const CITIES: City[] = [
  // Tier 1
  { slug: "mumbai", name: "Mumbai", state: "Maharashtra", tier: 1 },
  { slug: "delhi", name: "Delhi", state: "Delhi", tier: 1 },
  { slug: "bengaluru", name: "Bengaluru", state: "Karnataka", tier: 1 },
  { slug: "hyderabad", name: "Hyderabad", state: "Telangana", tier: 1 },
  { slug: "chennai", name: "Chennai", state: "Tamil Nadu", tier: 1 },
  { slug: "kolkata", name: "Kolkata", state: "West Bengal", tier: 1 },
  { slug: "pune", name: "Pune", state: "Maharashtra", tier: 1 },
  { slug: "ahmedabad", name: "Ahmedabad", state: "Gujarat", tier: 1 },
  // Tier 2
  { slug: "jaipur", name: "Jaipur", state: "Rajasthan", tier: 2 },
  { slug: "lucknow", name: "Lucknow", state: "Uttar Pradesh", tier: 2 },
  { slug: "chandigarh", name: "Chandigarh", state: "Chandigarh", tier: 2 },
  { slug: "indore", name: "Indore", state: "Madhya Pradesh", tier: 2 },
  { slug: "bhopal", name: "Bhopal", state: "Madhya Pradesh", tier: 2 },
  { slug: "nagpur", name: "Nagpur", state: "Maharashtra", tier: 2 },
  { slug: "surat", name: "Surat", state: "Gujarat", tier: 2 },
  { slug: "vadodara", name: "Vadodara", state: "Gujarat", tier: 2 },
  { slug: "coimbatore", name: "Coimbatore", state: "Tamil Nadu", tier: 2 },
  { slug: "kochi", name: "Kochi", state: "Kerala", tier: 2 },
  { slug: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh", tier: 2 },
  { slug: "patna", name: "Patna", state: "Bihar", tier: 2 },
  { slug: "ludhiana", name: "Ludhiana", state: "Punjab", tier: 2 },
  { slug: "agra", name: "Agra", state: "Uttar Pradesh", tier: 2 },
  { slug: "nashik", name: "Nashik", state: "Maharashtra", tier: 2 },
  { slug: "thane", name: "Thane", state: "Maharashtra", tier: 2 },
  { slug: "noida", name: "Noida", state: "Uttar Pradesh", tier: 2 },
  { slug: "gurugram", name: "Gurugram", state: "Haryana", tier: 2 },
  { slug: "faridabad", name: "Faridabad", state: "Haryana", tier: 2 },
  { slug: "ghaziabad", name: "Ghaziabad", state: "Uttar Pradesh", tier: 2 },
  // Tier 3
  { slug: "varanasi", name: "Varanasi", state: "Uttar Pradesh", tier: 3 },
  { slug: "kanpur", name: "Kanpur", state: "Uttar Pradesh", tier: 3 },
  { slug: "meerut", name: "Meerut", state: "Uttar Pradesh", tier: 3 },
  { slug: "allahabad", name: "Prayagraj", state: "Uttar Pradesh", tier: 3 },
  { slug: "ranchi", name: "Ranchi", state: "Jharkhand", tier: 3 },
  { slug: "jamshedpur", name: "Jamshedpur", state: "Jharkhand", tier: 3 },
  { slug: "raipur", name: "Raipur", state: "Chhattisgarh", tier: 3 },
  { slug: "amritsar", name: "Amritsar", state: "Punjab", tier: 3 },
  { slug: "jalandhar", name: "Jalandhar", state: "Punjab", tier: 3 },
  { slug: "dehradun", name: "Dehradun", state: "Uttarakhand", tier: 3 },
  { slug: "guwahati", name: "Guwahati", state: "Assam", tier: 3 },
  { slug: "bhubaneswar", name: "Bhubaneswar", state: "Odisha", tier: 3 },
  { slug: "mysuru", name: "Mysuru", state: "Karnataka", tier: 3 },
  { slug: "mangaluru", name: "Mangaluru", state: "Karnataka", tier: 3 },
  { slug: "thiruvananthapuram", name: "Thiruvananthapuram", state: "Kerala", tier: 3 },
  { slug: "madurai", name: "Madurai", state: "Tamil Nadu", tier: 3 },
  { slug: "tiruchirappalli", name: "Tiruchirappalli", state: "Tamil Nadu", tier: 3 },
  { slug: "vijayawada", name: "Vijayawada", state: "Andhra Pradesh", tier: 3 },
  { slug: "udaipur", name: "Udaipur", state: "Rajasthan", tier: 3 },
  { slug: "jodhpur", name: "Jodhpur", state: "Rajasthan", tier: 3 },
  { slug: "kota", name: "Kota", state: "Rajasthan", tier: 3 },
  { slug: "siliguri", name: "Siliguri", state: "West Bengal", tier: 3 },
  { slug: "aurangabad", name: "Aurangabad", state: "Maharashtra", tier: 3 },
];

export const getCity = (slug: string) => CITIES.find((c) => c.slug === slug);
