-- ============================================================
-- Velixa Capital — CRM Supabase schema
-- ------------------------------------------------------------
-- Run this ENTIRE script in the SQL Editor of your CRM Supabase project.
--
-- This project stores the application database:
--   users, employees, partners, leads, call assignments, call outcomes,
--   follow-ups, partner files, blogs, careers, credit cards,
--   affiliate links, audit logs.
--
-- PII columns (name, mobile, email, pan) are written AES-256-GCM
-- ENCRYPTED by the application layer (src/lib/crypto.ts). The raw
-- values in these columns are never readable from the DB directly —
-- even a SQL dump exposes no plaintext customer data.
--
-- NOTE: This schema mirrors the Prisma schema used for local dev
-- (prisma/schema.prisma). When you change one, update the other.
-- ============================================================

-- ---------- enums ----------
do $$ begin
  create type public.app_role as enum ('admin', 'user', 'partner', 'employee');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.lead_status as enum ('new', 'contacted', 'qualified', 'converted', 'lost');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.assignment_status as enum (
    'available', 'in_progress', 'success', 'rejected',
    'not_connected', 'reschedule', 'callback', 'converted', 'dnd'
  );
exception when duplicate_object then null; end $$;

-- ---------- users (application-side profiles; auth lives in the AUTH project) ----------
-- The `id` column here is a cuid generated by the app. It does NOT need to
-- match auth.users.id in the AUTH project — the link is by email.
create table if not exists public.users (
  id text primary key,
  email text unique not null,
  password_hash text,
  display_name text,
  role public.app_role not null default 'user',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists users_email_idx on public.users (email);

-- ---------- employees ----------
create table if not exists public.employees (
  id text primary key,
  user_id text unique not null references public.users(id) on delete cascade,
  full_name text not null,            -- encrypted
  mobile text not null,               -- encrypted
  email text not null,                -- encrypted
  employee_code text,
  designation text,
  target_calls integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists employees_is_active_idx on public.employees (is_active);

-- ---------- partner profiles ----------
create table if not exists public.partner_profiles (
  id text primary key,
  user_id text unique not null references public.users(id) on delete cascade,
  partner_code text,
  company_name text,
  mobile text,                        -- encrypted
  city text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- leads (public site form submissions) ----------
create table if not exists public.leads (
  id text primary key,
  created_at timestamptz not null default now(),
  name text not null,                 -- encrypted
  mobile text not null,               -- encrypted
  email text not null,                -- encrypted
  pan text,                           -- encrypted
  employment_type text,
  monthly_income numeric,
  business_details text,
  service text,
  loan_amount numeric,
  city text,
  message text,
  source_page text,
  status text not null default 'new',
  notes text,
  affiliate_id text,
  affiliate_slug text,
  assignment_id text unique
);
create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_status_idx on public.leads (status);

-- ---------- affiliate links ----------
create table if not exists public.affiliate_links (
  id text primary key,
  slug text unique not null,
  label text not null,
  target_url text not null,
  description text,
  clicks integer not null default 0,
  lead_count integer not null default 0,
  owner_id text references public.users(id) on delete set null,
  created_by text,
  created_at timestamptz not null default now()
);
create index if not exists affiliate_links_owner_idx on public.affiliate_links (owner_id);
create index if not exists affiliate_links_slug_idx on public.affiliate_links (slug);

-- ---------- partner applications (become-a-partner form) ----------
create table if not exists public.partner_applications (
  id text primary key,
  full_name text not null,
  mobile text not null,               -- encrypted
  email text not null,                -- encrypted
  pan text,                           -- encrypted
  city text not null,
  current_profession text,
  business_type text,
  experience_years integer not null default 0,
  expected_monthly_leads integer not null default 0,
  message text,
  source_page text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

-- ---------- call sheets ----------
create table if not exists public.call_sheets (
  id text primary key,
  name text not null,
  uploaded_by_id text references public.users(id) on delete set null,
  file_name text,
  total_records integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists call_sheets_created_at_idx on public.call_sheets (created_at desc);

-- ---------- call assignments (a lead routed to an employee) ----------
create table if not exists public.call_assignments (
  id text primary key,
  call_sheet_id text references public.call_sheets(id) on delete set null,
  employee_id text references public.employees(id) on delete set null,  -- null = available in universal pool
  customer_name text not null,        -- encrypted
  customer_mobile text not null,      -- encrypted
  customer_email text,                -- encrypted
  city text,
  service text,
  loan_amount numeric,
  employment_type text,
  monthly_income numeric,
  notes text,
  status text not null default 'available',
  priority integer not null default 0,
  assigned_at timestamptz not null default now(),
  claimed_at timestamptz,
  due_date timestamptz
);
create index if not exists assignments_employee_idx on public.call_assignments (employee_id);
create index if not exists assignments_status_idx on public.call_assignments (status);
create index if not exists assignments_sheet_idx on public.call_assignments (call_sheet_id);

-- ---------- call outcomes (one per logged call) ----------
create table if not exists public.call_outcomes (
  id text primary key,
  assignment_id text not null references public.call_assignments(id) on delete cascade,
  employee_id text references public.employees(id) on delete set null,
  outcome text not null,              -- connected|no_answer|wrong_number|busy|voicemail
  disposition text not null,          -- success|rejected|not_connected|reschedule|callback|converted|dnd
  call_duration_sec integer not null default 0,
  notes text,
  callback_at timestamptz,
  converted_amount numeric,
  created_at timestamptz not null default now()
);
create index if not exists outcomes_assignment_idx on public.call_outcomes (assignment_id);
create index if not exists outcomes_employee_idx on public.call_outcomes (employee_id);

-- ---------- follow-ups ----------
create table if not exists public.follow_ups (
  id text primary key,
  assignment_id text not null references public.call_assignments(id) on delete cascade,
  employee_id text references public.employees(id) on delete set null,
  scheduled_at timestamptz not null,
  note text,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists followups_assignment_idx on public.follow_ups (assignment_id);
create index if not exists followups_employee_idx on public.follow_ups (employee_id);
create index if not exists followups_scheduled_at_idx on public.follow_ups (scheduled_at);

-- ---------- partner files (loan doc / KYC uploads) ----------
create table if not exists public.partner_files (
  id text primary key,
  partner_id text references public.partner_profiles(id) on delete set null,
  customer_name text not null,        -- encrypted
  customer_mobile text not null,      -- encrypted
  customer_email text,                -- encrypted
  city text,
  service text,
  loan_amount numeric,
  employment_type text,
  file_name text,
  file_url text,                      -- encrypted storage path / key
  notes text,
  status text not null default 'new', -- new|in_review|submitted_to_bank|sanctioned|rejected
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists partner_files_partner_idx on public.partner_files (partner_id);
create index if not exists partner_files_status_idx on public.partner_files (status);

-- ---------- content tables ----------
create table if not exists public.blogs (
  id text primary key,
  slug text unique not null,
  title text not null,
  excerpt text default '',
  content text default '',
  cover_image text,
  author_id text references public.users(id) on delete set null,
  published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists blogs_published_idx on public.blogs (published);
create index if not exists blogs_published_at_idx on public.blogs (published_at desc);

create table if not exists public.credit_cards (
  id text primary key,
  slug text unique not null,
  name text not null,
  bank text not null,
  category text not null,
  image_url text,
  annual_fee numeric default 0,
  joining_fee numeric default 0,
  features text default '[]',         -- JSON string[]
  benefits text default '',
  affiliate_url text,
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists credit_cards_published_idx on public.credit_cards (published);

create table if not exists public.careers (
  id text primary key,
  title text not null,
  department text,
  location text default 'Remote / India',
  employment_type text default 'Full-time',
  short_description text not null,
  description text not null,
  requirements text default '[]',     -- JSON string[]
  salary_range text,
  apply_email text default 'careers@velixacapital.in',
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists careers_published_idx on public.careers (published);

-- ---------- audit log ----------
create table if not exists public.audit_logs (
  id text primary key,
  actor_id text references public.users(id) on delete set null,
  actor_role text,
  action text not null,
  entity text,
  entity_id text,
  meta text,                          -- JSON
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity);

-- ============================================================
-- Row Level Security
-- ------------------------------------------------------------
-- The app talks to this project using the SERVICE ROLE key from
-- server-side route handlers, which bypasses RLS. We still enable
-- RLS on every table as defence-in-depth — the anon key (which is
-- the only key that can reach the browser) is denied by default.
-- ============================================================

alter table public.users                 enable row level security;
alter table public.employees             enable row level security;
alter table public.partner_profiles      enable row level security;
alter table public.leads                 enable row level security;
alter table public.affiliate_links       enable row level security;
alter table public.partner_applications  enable row level security;
alter table public.call_sheets           enable row level security;
alter table public.call_assignments      enable row level security;
alter table public.call_outcomes         enable row level security;
alter table public.follow_ups            enable row level security;
alter table public.partner_files         enable row level security;
alter table public.blogs                 enable row level security;
alter table public.credit_cards          enable row level security;
alter table public.careers               enable row level security;
alter table public.audit_logs            enable row level security;

-- Public-read policies for published content (blogs, careers, cards).
-- These let the marketing site render without auth.
create policy "blogs_public_read" on public.blogs
  for select to anon, authenticated using (published = true);

create policy "careers_public_read" on public.careers
  for select to anon, authenticated using (published = true);

create policy "credit_cards_public_read" on public.credit_cards
  for select to anon, authenticated using (published = true);

create policy "affiliate_links_public_read" on public.affiliate_links
  for select to anon, authenticated using (true);

-- ============================================================
-- Storage bucket for partner file uploads
-- ------------------------------------------------------------
-- Creates the bucket if it doesn't exist. Set it to PRIVATE so
-- uploads/downloads go through signed URLs issued by the server.
-- ============================================================
insert into storage.buckets (id, name, public)
values ('partner-files', 'partner-files', false)
on conflict (id) do nothing;

-- ============================================================
-- updated_at trigger (auto-bump on every update)
-- ============================================================
create or replace function public.bump_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

do $$
declare t text;
begin
  for t in select unnest(array[
    'users','employees','partner_profiles','partner_files',
    'blogs','credit_cards','careers'
  ])
  loop
    execute format('drop trigger if exists %I on public.%I;', t || '_bump_updated_at', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.bump_updated_at();', t || '_bump_updated_at', t);
  end loop;
end $$;

-- ============================================================
-- DONE — CRM schema is ready.
-- Next: copy this project's URL + anon key + service role key into
-- .env.local under the CRM_* variables, and run the AUTH + CHAT
-- schemas in their respective projects.
-- ============================================================
